https://lectures.scientific-python.org/intro/numpy/

# Arrays

In [1]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
x.dtype

dtype('int64')

# Mixed types

In [3]:
y = np.array([1, "Ahmad", True])
y

array(['1', 'Ahmad', 'True'], dtype='<U21')

In [4]:
y[2] == True

False

In [5]:
z = np.array([1, 2])
z.dtype

dtype('int64')

In [6]:
z = np.array([1, 2.2])
z.dtype

dtype('float64')

# arange()

In [7]:
np.arange(3)

array([0, 1, 2])

In [8]:
np.arange(3.0).dtype

dtype('float64')

In [9]:
np.arange(3,7)

array([3, 4, 5, 6])

In [10]:
np.arange(3,7,2)

array([3, 5])

# bincount()

In [11]:
arr = np.array([1, 10, 1, 1, 1, 2, 2])
np.bincount(arr) 

array([0, 4, 2, 0, 0, 0, 0, 0, 0, 0, 1])

In [12]:
np.bincount(arr).size == np.amax(arr)+1

True

In [13]:
np.bincount(np.arange(5))

array([1, 1, 1, 1, 1])

# hstack() vs zip()

In [24]:
a = np.array([1,2,3])
b = np.array((4,5,6))
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [37]:
a = np.array([[1, 1, 1],[2, 2, 2],[3, 3, 3]])
print(a)
b = np.array([[4],[5], [6]])
c = np.array([[7],[8], [9]])
result = np.hstack((a,b,c))
result

[[1 1 1]
 [2 2 2]
 [3 3 3]]


array([[1, 1, 1, 4, 7],
       [2, 2, 2, 5, 8],
       [3, 3, 3, 6, 9]])

In [54]:
x = np.array([[1, 1, 1],[2, 2, 2],[3, 3, 3]])
y = np.array([[4,4,4],[5,5,5], [6,6,6]])
z = np.array([[7,7,7],[8,8,8], [9,9,9]])
res1 = list(zip(x,y,z))
res2 = list(zip(x[0], y[0], z[0]))
print(res1)
print(res2)

[(array([1, 1, 1]), array([4, 4, 4]), array([7, 7, 7])), (array([2, 2, 2]), array([5, 5, 5]), array([8, 8, 8])), (array([3, 3, 3]), array([6, 6, 6]), array([9, 9, 9]))]
[(1, 4, 7), (1, 4, 7), (1, 4, 7)]
